### PR TITLE
write conda rc file

### PR DESCRIPTION
**Pull request by bavardage**

### CODE REVIEW

**Comment by bavardage** [comment]
@justinuang @dansanduleac @jakobjuelich @derenrich

**Comment by gatesn** [comment]
@bavardage  Does it make sense for this to be a whole other task? We now have `bootstrapPython`, `configureCondaEnv`, `setupCondaBuild`, `setupPython`. If we're fine with this then it looks good

**Comment by bavardage** [comment]
not sure.. I was aiming to match the existing style of the plugin, which seemed to be a task for everything

**Comment by bavardage** [comment]
I'm fine with it, mainly for reasons of apathy vs any strong opinion one way or the other

**Comment by gatesn** [comment]
Fair point, I'm happy with this then

**Review by justinuang — APPROVED** [review]

**Comment by justinuang** [comment]
Can you reopen this pr not from a fork?

**Comment by bavardage** [comment]
yep

**Comment by bavardage** [comment]
...turns out, no - I don't have push permission to this repository still. You can set circle to allow builds of forks fwiw

**Pull request closed without merging**
